/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Metrics */
        get: operations["get_metrics_metrics_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ready */
        get: operations["ready_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/liquid/info": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liquid Info */
        get: operations["liquid_info_liquid_info_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/liquid/issuances": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liquid Issuances */
        get: operations["liquid_issuances_liquid_issuances_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/assets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Return a filtered asset catalog */
        get: operations["get_assets_assets_get"];
        put?: never;
        /** Submit an asset for review */
        post: operations["submit_asset_assets_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/assets/upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Submit an asset with an uploaded PDF document */
        post: operations["submit_asset_with_document_assets_upload_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/assets/{asset_id}/evaluate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Request AI evaluation for an owned asset */
        post: operations["request_asset_evaluation_assets__asset_id__evaluate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/assets/{asset_id}/tokenize": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Tokenize an approved asset into tradable fractions */
        post: operations["tokenize_asset_assets__asset_id__tokenize_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/assets/{asset_id}/document": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Download the managed PDF document for an asset */
        get: operations["download_asset_document_assets__asset_id__document_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/assets/{asset_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Return a single asset with AI and tokenization details */
        get: operations["get_asset_assets__asset_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AssetCreateRequest */
        AssetCreateRequest: {
            /** Name */
            name: string;
            /** Description */
            description: string;
            /**
             * Category
             * @enum {string}
             */
            category: "real_estate" | "commodity" | "invoice" | "art" | "other";
            /** Valuation Sat */
            valuation_sat: number;
            /**
             * Documents Url
             * Format: uri
             */
            documents_url: string;
        };
        /** AssetDetailOut */
        AssetDetailOut: {
            /** Id */
            id: string;
            /** Owner Id */
            owner_id: string;
            /** Name */
            name: string;
            /** Description */
            description: string;
            /**
             * Category
             * @enum {string}
             */
            category: "real_estate" | "commodity" | "invoice" | "art" | "other";
            /** Valuation Sat */
            valuation_sat: number;
            /** Documents Url */
            documents_url: string | null;
            document?: components["schemas"]["AssetDocumentOut"] | null;
            /**
             * Status
             * @enum {string}
             */
            status: "pending" | "evaluating" | "approved" | "rejected" | "tokenized";
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Ai Score */
            ai_score?: number | null;
            /** Ai Analysis */
            ai_analysis?: {
                [key: string]: unknown;
            } | null;
            /** Projected Roi */
            projected_roi?: number | null;
            token?: components["schemas"]["AssetTokenOut"] | null;
        };
        /** AssetDetailResponse */
        AssetDetailResponse: {
            asset: components["schemas"]["AssetDetailOut"];
        };
        /** AssetDocumentOut */
        AssetDocumentOut: {
            /** Storage Key */
            storage_key: string;
            /** Filename */
            filename: string;
            /** Content Type */
            content_type: string;
            /** Size Bytes */
            size_bytes: number;
        };
        /** AssetEvaluationRequestResponse */
        AssetEvaluationRequestResponse: {
            /** Message */
            message: string;
            /**
             * Estimated Completion
             * Format: date-time
             */
            estimated_completion: string;
        };
        /** AssetListResponse */
        AssetListResponse: {
            /** Assets */
            assets: components["schemas"]["AssetOut"][];
            /** Next Cursor */
            next_cursor: string | null;
        };
        /** AssetOut */
        AssetOut: {
            /** Id */
            id: string;
            /** Owner Id */
            owner_id: string;
            /** Name */
            name: string;
            /** Description */
            description: string;
            /**
             * Category
             * @enum {string}
             */
            category: "real_estate" | "commodity" | "invoice" | "art" | "other";
            /** Valuation Sat */
            valuation_sat: number;
            /** Documents Url */
            documents_url: string | null;
            document?: components["schemas"]["AssetDocumentOut"] | null;
            /**
             * Status
             * @enum {string}
             */
            status: "pending" | "evaluating" | "approved" | "rejected" | "tokenized";
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** AssetResponse */
        AssetResponse: {
            asset: components["schemas"]["AssetOut"];
        };
        /** AssetTokenOut */
        AssetTokenOut: {
            /** Id */
            id: string;
            /** Liquid Asset Id */
            liquid_asset_id: string;
            /** Total Supply */
            total_supply: number;
            /** Circulating Supply */
            circulating_supply: number;
            /** Unit Price Sat */
            unit_price_sat: number;
            /**
             * Visibility
             * @enum {string}
             */
            visibility: "public" | "private";
            /** Issuance Metadata */
            issuance_metadata?: {
                [key: string]: unknown;
            } | null;
            /**
             * Minted At
             * Format: date-time
             */
            minted_at: string;
        };
        /** AssetTokenizationRequest */
        AssetTokenizationRequest: {
            /** Liquid Asset Id */
            liquid_asset_id?: string | null;
            /** Taproot Asset Id */
            taproot_asset_id?: string | null;
            /** Total Supply */
            total_supply: number;
            /** Unit Price Sat */
            unit_price_sat: number;
            /**
             * Visibility
             * @default public
             * @enum {string}
             */
            visibility: "public" | "private";
        };
        /** Body_submit_asset_with_document_assets_upload_post */
        Body_submit_asset_with_document_assets_upload_post: {
            /** Name */
            name: string;
            /** Description */
            description: string;
            /**
             * Category
             * @enum {string}
             */
            category: "real_estate" | "commodity" | "invoice" | "art" | "other";
            /** Valuation Sat */
            valuation_sat: number;
            /** Document */
            document: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_metrics_metrics_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    ready_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    liquid_info_liquid_info_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    liquid_issuances_liquid_issuances_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    get_assets_assets_get: {
        parameters: {
            query?: {
                status?: ("pending" | "evaluating" | "approved" | "rejected" | "tokenized") | null;
                category?: ("real_estate" | "commodity" | "invoice" | "art" | "other") | null;
                cursor?: string | null;
                limit?: number;
            };
            header?: {
                "X-API-Key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssetListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    submit_asset_assets_post: {
        parameters: {
            query?: never;
            header?: {
                "X-API-Key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AssetCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssetResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    submit_asset_with_document_assets_upload_post: {
        parameters: {
            query?: never;
            header?: {
                "X-API-Key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_submit_asset_with_document_assets_upload_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssetResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    request_asset_evaluation_assets__asset_id__evaluate_post: {
        parameters: {
            query?: never;
            header?: {
                "X-API-Key"?: string | null;
            };
            path: {
                asset_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssetEvaluationRequestResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    tokenize_asset_assets__asset_id__tokenize_post: {
        parameters: {
            query?: never;
            header?: {
                "X-API-Key"?: string | null;
            };
            path: {
                asset_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AssetTokenizationRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssetDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    download_asset_document_assets__asset_id__document_get: {
        parameters: {
            query?: never;
            header?: {
                "X-API-Key"?: string | null;
            };
            path: {
                asset_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_asset_assets__asset_id__get: {
        parameters: {
            query?: never;
            header?: {
                "X-API-Key"?: string | null;
            };
            path: {
                asset_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssetDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
